// Code generated by gonstructor --type=App --constructorTypes=builder -init construct -propagateInitFuncReturns; DO NOT EDIT.

package main

import (
	"context"

	"github.com/docker/docker/client"
)

type AppBuilder struct {
	config  *Config
	context context.Context
	client  *client.Client
}

func NewAppBuilder() *AppBuilder {
	return &AppBuilder{}
}

func (b *AppBuilder) Config(config *Config) *AppBuilder {
	b.config = config
	return b
}

func (b *AppBuilder) Context(context context.Context) *AppBuilder {
	b.context = context
	return b
}

func (b *AppBuilder) Client(client *client.Client) *AppBuilder {
	b.client = client
	return b
}

func (b *AppBuilder) Build() (*App, error) {
	r := &App{
		config:  b.config,
		context: b.context,
		client:  b.client,
	}
	ret_construct0 := r.construct()
	return r, ret_construct0
}
