// Code generated by gonstructor --type=App --constructorTypes=builder -init construct -propagateInitFuncReturns; DO NOT EDIT.

package main

import (
	"context"

	"github.com/docker/docker/client"
)

type AppBuilder struct {
	context     context.Context
	client      *client.Client
	containerID string
}

func NewAppBuilder() *AppBuilder {
	return &AppBuilder{}
}

func (b *AppBuilder) Context(context context.Context) *AppBuilder {
	b.context = context
	return b
}

func (b *AppBuilder) Client(client *client.Client) *AppBuilder {
	b.client = client
	return b
}

func (b *AppBuilder) ContainerID(containerID string) *AppBuilder {
	b.containerID = containerID
	return b
}

func (b *AppBuilder) Build() (*App, error) {
	r := &App{
		context:     b.context,
		client:      b.client,
		containerID: b.containerID,
	}
	ret_construct0 := r.construct()
	return r, ret_construct0
}
