// Code generated by gonstructor --type=MountMapping --constructorTypes=builder -init construct -propagateInitFuncReturns; DO NOT EDIT.

package main

type MountMappingBuilder struct {
	target string
	device string
}

func NewMountMappingBuilder() *MountMappingBuilder {
	return &MountMappingBuilder{}
}

func (b *MountMappingBuilder) Target(target string) *MountMappingBuilder {
	b.target = target
	return b
}

func (b *MountMappingBuilder) Device(device string) *MountMappingBuilder {
	b.device = device
	return b
}

func (b *MountMappingBuilder) Build() (*MountMapping, error) {
	r := &MountMapping{
		target: b.target,
		device: b.device,
	}
	ret_construct0 := r.construct()
	return r, ret_construct0
}
