// Code generated by gonstructor --type=VolumeInit --constructorTypes=builder -init construct -propagateInitFuncReturns; DO NOT EDIT.

package main

import "time"

type VolumeInitBuilder struct {
	app        *App
	stackName  string
	mountPaths []string
	since      time.Time
}

func NewVolumeInitBuilder() *VolumeInitBuilder {
	return &VolumeInitBuilder{}
}

func (b *VolumeInitBuilder) App(app *App) *VolumeInitBuilder {
	b.app = app
	return b
}

func (b *VolumeInitBuilder) StackName(stackName string) *VolumeInitBuilder {
	b.stackName = stackName
	return b
}

func (b *VolumeInitBuilder) MountPaths(mountPaths []string) *VolumeInitBuilder {
	b.mountPaths = mountPaths
	return b
}

func (b *VolumeInitBuilder) Since(since time.Time) *VolumeInitBuilder {
	b.since = since
	return b
}

func (b *VolumeInitBuilder) Build() *VolumeInit {
	r := &VolumeInit{
		app:        b.app,
		stackName:  b.stackName,
		mountPaths: b.mountPaths,
		since:      b.since,
	}
	r.construct()
	return r
}
